services:
  db:
    image: ankane/pgvector:latest
    container_name: bmadflow-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bmadflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-bmadflow}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bmadflow}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bmadflow-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bmadflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      - bmadflow-network

networks:
  bmadflow-network:
    driver: bridge

volumes:
  postgres_data:
